version: '3.9'
services:
  web-app:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    networks:
      - todo-app
  
networks:
  todo-app:
    driver: bridge
    
